- hosts: localhost
  vars_files:
    - ./vars/defaults.yml

  pre_tasks:
    - name: bootstrap | install ansible-galaxy collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml

    - name: bootstrap | install ansible-galaxy roles
      ansible.builtin.command:
        cmd: ansible-galaxy role install -r roles/requirements.yml -f

- hosts: localhost
  become: true
  tasks:
    - name: apply configuration | deploy ansible roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      with_items:
        - sshConfig
        - ansible-pull
        - fedora-software
