- hosts: localhost
  pre_tasks:
    - name: bootstrap | install ansible-galaxy collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml

    - name: bootstrap | install ansible-galaxy roles
      ansible.builtin.command:
        cmd: ansible-galaxy role install -r roles/requirements.yml

  roles:
    - role: sshConfig
    - role: ansible-pull
